### ISSUE TITLE
Adding the capability to clear the code!

### ISSUE THREAD

**Issue by dev-ramiroleandrodiaz** [posix88/FasterVerificationCode#2]
Hi @posix88 I would like to add the capability to clear the code. Really easy, I really need it and I think some people can need it as well. Can I submit a PR for you to review?

**Comment by posix88** [comment]
hello @dev-ramiroleandrodiaz sure 👍

**Comment by ramiroleandrodiaz** [comment]
Hi @posix88, it's me from a different account haha. I want to push a new branch in order to submit a PR for you to see it but I don't have permissions. How shall we proceed?

**Comment by posix88** [comment]
Feature added with #3
