### ISSUE TITLE
Fixed carrier animation size & Corrected clearCode function

### ISSUE THREAD

**Issue by ramiroleandrodiaz** [posix88/FasterVerificationCode#6]
Hi @posix88 I added some more few tweaks. The first one to the one I made myself, the function clear code was clearing the Code but it was not letting the user continue typing again, and the second is a fix for something I found, you can seen it better in the PR's description.

**Comment by posix88** [comment]
hello @ramiroleandrodiaz I'll check it

**Comment by posix88** [comment]
fixed in  #5
